USE ROLE ACCOUNTADMIN;

USE WAREHOUSE COMPUTE_WH;

CREATE DATABASE MYBD;

CREATE SCHEMA MYSCHEMA;

-- CREATE PERMANENT TABLE 

CREATE TABLE PERMANENT_TABLE
(
ID INT,
NAME STRING
);

ALTER TABLE PERMANENT_TABLE SET DATA_RETENTION_TIME_IN_DAYS = 10;

CREATE TEMPORARY TABLE TEMPORARY_TABLE
(
ID INT,
NAME STRING
);

ALTER TABLE TEMPORARY_TABLE SET DATA_RETENTION_TIME_IN_DAYS = 1;

CREATE TRANSIENT TABLE TRANSIENT_TABLE
(
ID INT,
NAME STRING
);

ALTER TABLE TRANSIENT_TABLE SET DATA_RETENTION_TIME_IN_DAYS = 1;

SHOW TABLES;

CREATE TABLE EMPLOYEE
(
ID INT,
NAME VARCHAR(50),
AGE INT,
DEPARTMENT VARCHAR(50),
SALARY INT
);

INSERT INTO EMPLOYEE (ID, NAME, AGE, DEPARTMENT, SALARY) VALUES
(1, 'KAZIM', 21, 'REGISTRAR', 25000),
(2, 'ALI', 25, 'HR', 30000),
(3, 'AHMED', 28, 'IT', 40000),
(4, 'SARA', 24, 'FINANCE', 35000),
(5, 'FATIMA', 27, 'MARKETING', 32000);

SELECT * FROM EMPLOYEE;

-- STANDARD VIEW (SIMPLE VIEW TYPE)

CREATE VIEW IT_EMPLOYEE AS
SELECT ID, NAME, SALARY FROM EMPLOYEE
WHERE ID BETWEEN 1 AND 3;

SELECT * FROM IT_EMPLOYEE;

-- SECURE VIEW 

CREATE OR REPLACE SECURE VIEW HR_EMPLOYEE_VIEW AS
SELECT * FROM EMPLOYEE
WHERE DEPARTMENT = 'HR';

SELECT * FROM HR_EMPLOYEE_VIEW;

-- MATERALIZED VIEW

CREATE MATERIALIZED VIEW mv_it_employee AS
SELECT ID, NAME, SALARY
FROM EMPLOYEE
WHERE DEPARTMENT = 'IT';

SELECT * FROM mv_it_employee;

CREATE MATERIALIZED VIEW MV_EMPLOYEE AS
SELECT DEPARTMENT, SUM(SALARY) AS TOTAL_SALARY
FROM EMPLOYEE
WHERE SALARY BETWEEN 25000 AND 35000
GROUP BY DEPARTMENT;

SELECT * FROM MV_EMPLOYEE;

SHOW VIEWS;


-- Snowflake stages 

CREATE TABLE CUSTOMER_DETAILS (
    CUSTOMER_ID INT,
    NAME VARCHAR(50),
    AGE INT,
    CITY VARCHAR(50),
    PHONE VARCHAR(15),
    EMAIL VARCHAR(100)
);

-- TABLE STAGE 

LIST @%CUSTOMER_DETAILS;

-- USER STAGE 

LIST @~;

-- CREATE THE NAMED STAGE

CREATE STAGE CUSTOMER_STAGE;

LIST @CUSTOMER_STAGE;
-- TO CHECK DATA IS HERE
SELECT * FROM CUSTOMER_DETAILS;
-- NEED TO TRUNCATE THE TABLE
TRUNCATE TABLE CUSTOMER_DETAILS;

SELECT * FROM CUSTOMER_DETAILS;

-- LOAD DATA INTO THE CUSTOMER_DETAILS TABLE USING QUERY

COPY INTO CUSTOMER_DETAILS
FROM @CUSTOMER_STAGE
FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1);

SELECT * FROM CUSTOMER_DETAILS;

-- STUDENT STAGE CREATE 

--CREATE TABLE 
CREATE TABLE STUDENT (
    STUDENT_ID INT,
    NAME VARCHAR(50),
    AGE INT,
    CLASS VARCHAR(20),
    CITY VARCHAR(50),
    MARKS INT
);

CREATE STAGE STUDENT_STAGE;

LIST @STUDENT_STAGE;

-- LOAD DATA 
COPY INTO STUDENT
FROM @STUDENT_STAGE
FILE_FORMAT = (TYPE = 'CSV' SKIP_HEADER = 1);

SELECT * FROM STUDENT;

TRUNCATE TABLE STUDENT;

SELECT * FROM STUDENT;

-- CREATE CSV FORMAT
CREATE FILE FORMAT CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
RECORD_DELIMITER = '\n'
SKIP_HEADER = 1;

--LOAD DATA IN THE STUDENT TABLE USING FILE FORMAT
COPY INTO STUDENT
FROM @STUDENT_STAGE
FILE_FORMAT = (FORMAT_NAME = CSV_FORMAT);

SELECT * FROM STUDENT;

-- snowflake streaming

CREATE TABLE COMPANY (
    ID INT,
    NAME STRING,
    SALARY INT
);

-- CREATE STREAM 
CREATE STREAM COMPANY_STREAM ON TABLE COMPANY;

INSERT INTO COMPANY VALUES (1, 'Ali', 25000);

-- SELECT TO SEE COMING DATA
SELECT * FROM COMPANY_STREAM;

INSERT INTO COMPANY VALUES (2, 'hASSAN', 30000);

SELECT * FROM COMPANY_STREAM;

-- CHECK latest changes (INSERT, UPDATE, DELETE)

SELECT ID, NAME, SALARY, METADATA$ACTION  
FROM COMPANY_STREAM;

-- stream task data -- automatically SQL ki Query run karta hai 

-- Source Table (STUDENT)
CREATE TABLE UNIVERSITY (
    STUDENT_ID INT,
    NAME STRING,
    DEPARTMENT STRING,
    CGPA FLOAT
);

-- Initial Data Insert

INSERT INTO UNIVERSITY VALUES
(1, 'Ali', 'CS', 3.2),
(2, 'Ahmed', 'IT', 3.5);

-- Target Table

CREATE TABLE UNIVERSITY_TARGET (
    STUDENT_ID INT,
    NAME STRING,
    DEPARTMENT STRING,
    CGPA FLOAT
);

-- Stream Create

CREATE STREAM UNIVERSITY_stream ON TABLE UNIVERSITY;

-- New Data Insert (Testing)

INSERT INTO UNIVERSITY VALUES
(3, 'Sara', 'CS', 3.8),
(4, 'Ayesha', 'SE', 3.6);

-- Ye changes stream mein capture ho jayenge
-- Task Create

CREATE TASK process_UNIVERSITY_stream
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
AS
INSERT INTO UNIVERSITY_TARGET
SELECT STUDENT_ID, NAME, DEPARTMENT, CGPA
FROM UNIVERSITY_stream
WHERE METADATA$ACTION = 'INSERT';

-- Task Start

ALTER TASK process_UNIVERSITY_stream RESUME;

SELECT * FROM UNIVERSITY_TARGET;

SELECT * FROM UNIVERSITY;

SELECT *, METADATA$ACTION 
FROM UNIVERSITY_stream;

